### ISSUE TITLE
Uncaught Exception with node-red-conbtrib-re-postgres

### ISSUE THREAD

**Issue by mhechthz** [unirobot/node-red-contrib-postgres#11]
Hi,

I'm not sure whether or not I'm right here, because I have an issue with node-red-conbtrib-re-postgres which is pobably not the same as node-red-contrib-postgres.

If I inject a msg.topic="select ..." and let the msg.payload at the injected timestamp, I get:

```
18 Mar 19:34:19 - [red] Uncaught Exception:
18 Mar 19:34:19 - TypeError: Cannot create property 'values' on number '1584556459764'
    at Object.normalizeQueryConfig (/home/di29394/.node-red/node_modules/pg/lib/utils.js:148:21)
    at new Query (/home/di29394/.node-red/node_modules/pg/lib/query.js:23:18)
    at Client.query (/home/di29394/.node-red/node_modules/pg/lib/client.js:479:13)
    at Client.patchedQuery [as query] (/home/di29394/.node-red/node_modules/node-postgres-named/main.js:60:14)
    at PendingItem.node.pgpool.connect [as callback] (/home/di29394/.node-red/node_modules/node-red-contrib-re-postgres/lib/pg.js:73:21)
    at Pool._acquireClient (/home/di29394/.node-red/node_modules/pg-pool/index.js:271:21)
    at client.connect (/home/di29394/.node-red/node_modules/pg-pool/index.js:234:21)
    at Connection.<anonymous> (/home/di29394/.node-red/node_modules/pg/lib/client.js:234:7)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:121:20)
```
Topic is used e.g. for mysql node. Nevertheless, the node-red server shouldn't crash.

Best regards

Michael

**Comment by okhiroyuki** [comment]
@mhechthz 
Thank you for reporting on the issue.
Where can I find more information about node-red-conbtrib-re-postgres?

**Comment by mhechthz** [comment]
I only know this page: https://flows.nodered.org/node/node-red-contrib-re-postgres

**Comment by okhiroyuki** [comment]
@mhechthz 
Thank you for your reply.

node-red-conbtrib-re-postgres is closed source code, so it is unknown whether it is the same as our node. If you have any problems using our nodes, please tell us, including how to reproduce them.
